# GLOBAL CONFIGURATION
spring:
    # if you want to set a different profile
    # use environment variable:
    #
    # SPRING_PROFILES_ACTIVE=docker
    profiles.active: local
    application.name: Zuul

# zuul proxy always exposes 8080 
server.port: 8080

# zuul routes
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ignoredServices: '*'
  prefix: /api
  routes:
    clientes-api-docs:
      strip-prefix: true
      path: /clientes/**
      serviceId: clientes
    clientes:
      strip-prefix: false
      path: /v1/clientes/**
      serviceId: clientes
    # routes for service 'filmes'
    filmes-api-docs:
      strip-prefix: true
      path: /filmes/**
      serviceId: filmes
    filmes:
      strip-prefix: false
      path: /v1/filmes/**
      serviceId: filmes
    # routes for service 'servicos'
    servicos-api-docs:
      strip-prefix: true
      path: /servicos/**
      serviceId: servicos
    servicos:
      strip-prefix: false
      path: /v1/servicos/**
      serviceId: servicos

---
# LOCAL CONFIGURATION
spring:
    profiles: local
      
      
eureka:
  client:
    # in local mode you have to run your service 
    # discovery on localhost (you also can run the 
    # cloud infrastructure on your local docker host)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # fetch all 5 seconds the delta from the service registry
    registry-fetch-interval-seconds: 5
    instance:
      status-page-url: http://localhost:8080/swagger-ui.html

---
# DOCKER CONFIGURATION
spring:
    profiles: docker
    

eureka:
  client:
    # the hostname of your eureka server should be 'discovery'
    serviceUrl.defaultZone: http://discovery:8761/eureka/
    # fetch all 5 seconds the delta from the service registry
    registry-fetch-interval-seconds: 5
  instance:
    status-page-url: http://localhost:8080/swagger-ui.html

