version: '2'

services:
  # --------------
  # database
  # --------------
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: netflixusr
        MYSQL_PASSWORD: netflix123
        MYSQL_DATABASE: netflix

  # --------------
  # phpadmin
  # --------------
  phpadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8081:80"

  # --------------
  # rabbitmq
  # --------------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672"
      - "25672"
    hostname: rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: netflixusr
        RABBITMQ_DEFAULT_PASS: netflix123

  # --------------
  # registry
  # --------------
  discovery:
    image: 1tiquinho/startupone:discovery2.0
    ports:
      - "8761:8761"
    hostname: discovery
    environment:
        SPRING_PROFILES_ACTIVE: docker

  # --------------
  # zuul proxy
  # --------------
  zuul:
    image: 1tiquinho/startupone:zuul4.0
    ports:
      - "80:8080"
    hostname: zuul
    links:
      - discovery
    environment:
        SPRING_PROFILES_ACTIVE: docker

  # --------------
  # clientes
  # --------------
  clientes:
    image: 1tiquinho/startupone:clientes4.0
    ports:
      - "8080"
    hostname: clientes
    links:
      - discovery
      - rabbitmq
    environment:
        SPRING_PROFILES_ACTIVE: docker
        MYSQL_URL: "jdbc:mysql://mysql:3306/netflix"
        MYSQL_USER: netflixusr
        MYSQL_PASS: netflix123
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USERNAME: netflixusr
        RABBITMQ_PASSWORD: netflix123

  # --------------
  # filmes
  # --------------
  filmes:
    image: 1tiquinho/startupone:filmes4.0
    ports:
      - "8080"
    hostname: filmes
    links:
      - discovery
      - rabbitmq
    environment:
        SPRING_PROFILES_ACTIVE: docker
        MYSQL_URL: "jdbc:mysql://mysql:3306/netflix"
        MYSQL_USER: netflixusr
        MYSQL_PASS: netflix123
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USERNAME: netflixusr
        RABBITMQ_PASSWORD: netflix123

  # --------------
  # servicos
  # --------------
  servicos:
    image: 1tiquinho/startupone:servicos4.0
    ports:
      - "8080"
    hostname: servicos
    links:
      - discovery
      - rabbitmq
    environment:
        SPRING_PROFILES_ACTIVE: docker
        MYSQL_URL: "jdbc:mysql://mysql:3306/netflix"
        MYSQL_USER: netflixusr
        MYSQL_PASS: netflix123
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USERNAME: netflixusr
        RABBITMQ_PASSWORD: netflix123

